name: Checks

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          pip install -U poetry
          poetry install --no-root
      - name: Lint
        run: |
          poetry run ruff check .
      - name: Format
        run: |
          poetry run ruff format .
      # - name: Type check
      #   run: |
      #     poetry run mypy .
      - name: Create requirements.txt for Audit
        run: |
          poetry self add poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt
      - name: Audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
      - name: Test
        run: |
          poetry run pytest
